name: Go build and test
env:
  GO111MODULE: "on"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.0-rc1
      
    - name: Build
      run: go build -v ./...
      working-directory: src

    - name: Test
      run: go test -short -v ./...
      working-directory: src

    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
